name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # <<< AÑADE ESTO >>>
    env:
      DATABASE_URL: "mysql://user:pass@127.0.0.1:3306/_ci_dummy"
      SHADOW_DATABASE_URL: "mysql://user:pass@127.0.0.1:3306/_ci_shadow"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Prisma format & validate
        run: |
          npx prisma format --schema=prisma/schema.prisma
          npx prisma validate --schema=prisma/schema.prisma

      - name: Prisma generate
        run: npx prisma generate --schema=prisma/schema.prisma

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint
        run: npx next lint

      - name: Build
        run: npm run build
